### ISSUE TITLE
[FEATURE] Add data sources for listing resources

### ISSUE THREAD

**Issue by lechnerc77** [cloudfoundry/terraform-provider-cloudfoundry#17]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

Currently only a read for one instance for a resource is available. However a list of available instances of a resource is not available as a data source.  

Example: cloudfoundry_app is available as data source, but I cannot list all apps via cloudfoundry_app**s**

The corresponding API endpoints on CF side are available see e.g., https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#apps

### Describe the solution you would like

Add data sources should support the fetching of a list of resources not only one dedicated resource. 

### Describe alternatives you have considered

n/a

### Additional context

n/a

**Comment by lechnerc77** [comment]
Here a list of data sources that should offer a list operation

| Resource | Proposed Name of Data Source | Link to CF V3 API
| --- | --- | ---
| Apps                           | cloudfoundry_apps                             | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-apps>
| Domain                         | cloudfoundry_domains                          | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-domains>
| Isolation Segment              | cloudfoundry_isolation_segments               | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-isolation-segments>
| Orgs                           | cloudfoundry_orgs                             | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-organizations>
| Org Quota                      | cloudfoundry_org_quotas                       | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-organization-quotas>
| Role                           | cloudfoundry_roles                            | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-roles>
| Routes                         | cloudfoundry_routes                           | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-routes>
| Security Group                 | cloudfoundry_security_groups                  | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-security-groups>
| Service                        | cloudfoundry_services                         | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-service-offerings>
| Service Credential Binding     | cloudfoundry_service_credential_bindings      | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-service-credential-bindings>
| Service Instance               | cloudfoundry_service_instances                | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-service-instances>
| Space                          | cloudfoundry_spaces                           | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-spaces>
| Space Quota                    | cloudfoundry_space_quotas                     | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-space-quotas>
| Space Stack                    | cloudfoundry_stacks                           | <https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-stacks  >

**Comment by lechnerc77** [comment]
For MTA see https://github.com/cloudfoundry/terraform-provider-cloudfoundry/issues/25

**Comment by Dray56** [comment]
All data sources mentioned have been implemented
