### ISSUE TITLE
[BUG] Inconsistent naming of resource `service`

### ISSUE THREAD

**Issue by lechnerc77** [cloudfoundry/terraform-provider-cloudfoundry#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0-rc1

### What version of the Terraform CLI are you using?

1.9.0

### What CF API version are you using?

3.137

### What type of issue are you facing

bug report

### Describe the bug

The resources of the provider should reflect the underlying resources defined by the CF API. This is quite consistent except for the resource [service](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/data-sources/service). This represents the resource `service offering` (https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#service-offerings) and should be named accordingly.

### Expected Behavior

The Terraform resources reflect the resources from the CF API. Consequently the `service offering` of the CF API is reflected by a resource/datasource `cloudfoundry_service_offering`

### Steps To Reproduce

n/a

### Your Terraform Configuration

```hcl
n/a
```

### Roles

n/a

### Add screenshots to help explain your problem

n/a

### Additional context

n/a

**Comment by vipinvkmenon** [comment]
The idea for the creation of a `service` datasource was to emulate the [cloudfoundry_service ](https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs/data-sources/service)of the community. In the V3 approach, the service-offering object does not give the service-plans directly. From a user perspective, typically users are used to referring to the service with the service plan.

On a closer look at the [service-plans](https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#list-service-plans) API, this looks like the resource that will be needed to get the details of a particular service-offering + plan. So a datasource named `service_plans` will be created.
