### ISSUE TITLE
[BUG] Add Migration guide to Terraform registry documentation

### ISSUE THREAD

**Issue by lechnerc77** [cloudfoundry/terraform-provider-cloudfoundry#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0-rc1

### What version of the Terraform CLI are you using?

n/a

### What CF API version are you using?

n/a

### What type of issue are you facing

documentation issue

### Describe the bug

The migration guide paving the path from the outdated community provider should be stressed more in the repository as well as in the Terraform documentation.

### Expected Behavior

- A dedicated section on the migration should be available in the `README.md` of the repository
- The Migration guide should be referenced in the provider documentation of the Terraform registry (https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs)

### Steps To Reproduce

n/a

### Your Terraform Configuration

```hcl
n/a
```

### Roles

n/a

### Add screenshots to help explain your problem

n/a

### Additional context

n/a

**Comment by lechnerc77** [comment]
The README.md of the migration guide should also be updated ot the latest Terraform provider version and reference the right provider (`cloudfoundry/cloudfoundry` instead of `SAP/cloudfoundry`)

**Comment by Dray56** [comment]
fixed by #33
