### ISSUE TITLE
[BUG] Inconsistency of resources for roles and data sources

### ISSUE THREAD

**Issue by lechnerc77** [cloudfoundry/terraform-provider-cloudfoundry#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0-rc1

### What version of the Terraform CLI are you using?

1.9.5

### What CF API version are you using?

3.137

### What type of issue are you facing

bug report

### Describe the bug

The resources and data sources to assign and read roles of users are not consistent. While the resources distinguish the levels of organization and space ([org_role](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/resources/org_role), [space_role](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/resources/space_role)), the data source is a single one for all levels ([role](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/data-sources/role)).

### Expected Behavior

Data sources for the org and space level are available in analogy to the resources

### Steps To Reproduce

n/a

### Your Terraform Configuration

```hcl
n/a
```

### Roles

n/a

### Add screenshots to help explain your problem

n/a

### Additional context

n/a

**Comment by vipinvkmenon** [comment]
The resources `org_role` and `space_role` were created as a convenience for the end user. The underlying API for both is [roles](https://v3-apidocs.cloudfoundry.org/version/3.179.0/index.html#roles) API. From the API definition, it does not really distinguish between a space-role and an org-role. It only needs to role-guid to get the details. So even if we create 2 datasources for space_role and org_role it would be the same call and the same structure inside. 

We could maybe validate whether the given role-GUID is a valid space-role or org-role depending on the type of data source 🤔

**Comment by lechnerc77** [comment]
@vipinvkmenon I think you can follow the same approach as for the resource: 
For the data source for org roles the interface only supports an `org_id`, while for space roles `org_id` and `space_id` are mandatory parameters
