### ISSUE TITLE
[BUG] License Section pointing to SAP

### ISSUE THREAD

**Issue by lechnerc77** [cloudfoundry/terraform-provider-cloudfoundry#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

all

### What version of the Terraform CLI are you using?

1.9.5

### What CF API version are you using?

n/a

### What type of issue are you facing

documentation issue

### Describe the bug

The "License" section in the README.md still points to SAP (https://github.com/cloudfoundry/terraform-provider-cloudfoundry?tab=readme-ov-file#licensing). However the provider is now under the CF Foundation and this should be reflected in this section.

### Expected Behavior

License statement reflects the ownership of CF foundation

### Steps To Reproduce

n/a

### Your Terraform Configuration

```hcl
n/a
```

### Roles

n/a

### Add screenshots to help explain your problem

n/a

### Additional context

n/a

**Comment by v0lkc** [comment]
It's not only the license statement, but there are also plenty of other references which I think should be removed or updated. Just to give you some examples:


* SAP Code of Conduct --> https://github.com/cloudfoundry/terraform-provider-cloudfoundry/blob/17cd4adda49228e61f06b1ae266041a6e12bbd5a/CONTRIBUTING.md?plain=1#L5
* OSPO --> https://github.com/cloudfoundry/terraform-provider-cloudfoundry/blob/17cd4adda49228e61f06b1ae266041a6e12bbd5a/.reuse/dep5#L3
* URLs refering to the former repository in the SAP org --> https://github.com/cloudfoundry/terraform-provider-cloudfoundry/blob/17cd4adda49228e61f06b1ae266041a6e12bbd5a/DEVELOPER.md?plain=1#L136
*  "SAP Cloud Foundry Provider" in the migration guide
* and so on



https://github.com/search?q=repo%3Acloudfoundry%2Fterraform-provider-cloudfoundry%20sap&type=code
