### ISSUE TITLE
[BUG] Impossible to import org_role with username

### ISSUE THREAD

**Issue by MarcusNotheis** [cloudfoundry/terraform-provider-cloudfoundry#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.1.0

### What version of the Terraform CLI are you using?

1.9.8

### What CF API version are you using?

3.180.0

### What type of issue are you facing

bug report

### Describe the bug

It is currently not possible to import existing roles into the resource `cloudfoundry_org_role` when the `username` property is used.
When importing an existing role-guid, the provider tries to recreate the role `organization_user`, but the CF API returns an error if the user is still assigned to spaces.

### Expected Behavior

Import of existing roles should be supported.

### Steps To Reproduce

1. Execute `terraform init`
2. fill placeholders with valid org-id, role-guid and email address
3. run terraform `apply`

### Your Terraform Configuration

```hcl
terraform {
  required_providers {
    cloudfoundry = {
      source  = "cloudfoundry/cloudfoundry"
      version = "~> 1.0"
    }
  }
}

# CF Provider configured via env vars
# https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs
provider "cloudfoundry" {}

import {
    to = cloudfoundry_org_role.my_org_user
    id = "role-guid-for-organization_user"
}

resource "cloudfoundry_org_role" "my_org_user" {
  org      = "org-guid"
  type     = "organization_user"
  username = "any.valid@mail.address"
}
```

### Roles

- Org Manager
- BTP Subaccount Admin

### Add screenshots to help explain your problem

Log Output:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # cloudfoundry_org_role.my_org_user must be replaced
  # (imported from "<REDACTED_ROLE_GUID>")
  # Warning: this will destroy the imported resource
-/+ resource "cloudfoundry_org_role" "my_org_user" {
      ~ created_at = "2023-03-17T15:12:00Z" -> (known after apply)
      ~ id         = "<REDACTED_ROLE_GUID>" -> (known after apply)
        org        = "<REDACTED_ORG_GUID>"
        type       = "organization_user"
      ~ updated_at = "2023-03-17T15:12:00Z" -> (known after apply)
      ~ user       = "<REDACTED_USER_GUID>" -> (known after apply) # forces replacement
      + username   = "<REDACATED_MAIL>" # forces replacement
    }

Plan: 1 to import, 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudfoundry_org_role.my_org_user: Importing... [id=<REDACTED_ROLE_GUID>]
cloudfoundry_org_role.my_org_user: Import complete [id=<REDACTED_ROLE_GUID>]
cloudfoundry_org_role.my_org_user: Destroying... [id=<REDACTED_ROLE_GUID>]
╷
│ Error: API Error Deleting Role
│ 
│ Could not delete the role with ID <REDACTED_ROLE_GUID> and user ID <REDACTED_USER_GUID> : executing DELETE request for /v3/roles/<REDACTED_ROLE_GUID> failed: cfclient error (CF-UnprocessableEntity|10008): Cannot delete organization_user role while user has roles in spaces in that organization.
╵
```

### Additional context

The import is working fine if the `user` guid is used instead of the `username` with the mail address.

**Comment by MarcusNotheis** [comment]
Thanks for looking into this, @vipinvkmenon!
Using the `user` datasource is something we've already looked into as well, but one thing we're currently struggeling with is the following:
How can we then add new users? 
Should we then manage all users in terraform using the [cloudfoundry_user resource](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/resources/user), and then assign via the org_role via the resulting guids?

**Comment by vipinvkmenon** [comment]
Hi @MarcusNotheis ,

Yes you are right in the approach as far as BTP is concerned. As side note the only time we can create users on cf is when we are the cf-admin which is not the case in BTP.
So for CF in BTP, the use must login to cf at least once for it to be available.
