### ISSUE TITLE
[FEATURE] Assign existing security groups to a space

### ISSUE THREAD

**Issue by rahearn** [cloudfoundry/terraform-provider-cloudfoundry#81]
### What area do you want to see improved?

terraform provider

### Is your feature request related to a problem? Please describe.

There doesn't appear to be a way to assign an existing named security group to a space, either on space creation or as a separate resource.

### Describe the solution you would like

I'd like to be able to do something like the following:

```
data "cloudfoundry_security_group" "trusted_egress" {
  name = "existing_egress_security_group"
}

resource "cloudfoundry_space" "app_space" {
  org = local.org_id
  name = local.space_name
}

resource "cloudfoundry_bound_security_group" "space_egress" {
  security_group = data.cloudfoundry_security_group.trusted_egress.id
  type = "running"
  spaces = [cloudfoundry_space.app_space.id]
}
```

### Describe alternatives you have considered

The existing `cloudfoundry_security_group` resource is not accessible at the level of permission that I have, which can call both `cf create-space` and `cf bind-security-group` if I were using the CLI, so there do not appear to be any alternatives within this provider.

**Comment by vipinvkmenon** [comment]
Considering the [API](https://v3-apidocs.cloudfoundry.org/version/3.181.0/index.html#bind-a-running-security-group-to-spaces) is designed, we will need to create a new resource for managing bindings.

**Comment by vipinvkmenon** [comment]
Its been assigned for immediate pickup @rahearn 
considering the API documentation and the cf-cli and intuitive name for the resource would be `security_group_binding` and lifecycle = running/staging etc..

**Comment by Dray56** [comment]
It would be better to have attributes `running_spaces` and `staging_spaces` similar to that of `security_group` resource instead.
I think  `security_group_spaces_bindings` would be more apt as a name. This makes it specific and obvious.
